# Generated by Django 6.1.1 on 2026-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phonenumberverification_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Account signup'), ('change', 'Phone number change'), ('login', 'Sign-in verification')], default='signup', max_length=10),
        ),
    ]
