# Generated by Django 6.1.1 on 2026-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
    ]
