# Generated by Django 5.2.17 on 2026-09-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_verification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('accent', models.CharField(default='#a78bfa', max_length=9)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away'), ('dnd', 'Do not disturb'), ('invisible', 'Invisible')], default='available', max_length=12)),
                ('enter_to_send', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('sounds_enabled', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('typing_indicator', models.BooleanField(default=True)),
                ('last_seen_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user preferences',
            },
        ),
    ]
