# Generated by Django 5.2.17 on 2026-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='accent',
            field=models.CharField(default='#74ffd6', max_length=9),
        ),
    ]
