# Generated by Django 5.2.17 on 2026-09-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pushdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='accounts_pu_user_id_2c1509_idx',
            old_name='accounts_p_user_id_idx',
        ),
    ]
