# Generated by Django 5.2.17 on 2026-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_vapidkey_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discoverable_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable_by_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable_in_suggestions',
            field=models.BooleanField(default=True),
        ),
    ]
