# Generated by Django 5.2.17 on 2026-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
