# Generated by Django 6.1.1 on 2026-09-19 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_created_by_conversation_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nickname', 'contact__first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='direct_key',
            field=models.CharField(blank=True, editable=False, help_text='Stable sorted participant key for direct conversations.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('recipient', 'message', 'kind'), name='unique_message_notification_per_recipient'),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blockeduser',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_per_user'),
        ),
        migrations.AddConstraint(
            model_name='blockeduser',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_cannot_be_self'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'created_at'], name='messaging_c_owner_i_8aa4ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('owner', 'contact'), name='unique_contact_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('owner', models.F('contact')), _negated=True), name='contact_cannot_be_self'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported', '-created_at'], name='messaging_u_reporte_c89f05_idx'),
        ),
    ]
