# Generated by Django 5.2.17 on 2026-09-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagevisibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='User archived this conversation.'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='User muted notifications for this conversation.'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='User pinned this conversation to the top of their list.'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'is_archived'], name='messaging_c_user_id_cac884_idx'),
        ),
        migrations.AddField(
            model_name='messageuserstate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messageuserstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['user', 'is_starred'], name='messaging_m_user_id_ff4b23_idx'),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['message', 'user'], name='messaging_m_message_8345bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageuserstate',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_user_state'),
        ),
    ]
